# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 研究方向
    url: research
    weight: 1

  - name: 研究团队
    url: team
    weight: 2

  - name: 科研成果
    url: publications
    weight: 3

  - name: 新闻动态
    url: news
    weight: 4

  - name: 加入我们
    url: join
    weight: 5

  - name: 联系我们
    url: contact
    weight: 6